//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by tools/generate-conditions.js.
//     Source: lib/js/weather/conditions.js
//
//     Changes to this file may be lost if the code is regenerated.
//     Edit the source vocabulary and run `npm run gen:conditions` instead.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once

// every condition token (day then night, adjacent) plus one bogus token that exercises
// the WI_NA fallback. dev-only - a face names this only from inside its own #if DEV_MODE,
// so a release build never links it. the icon walk taps through the list in order.
static const char *const wx_dev_condition_tokens[] = {
    "CLEAR", "CLEAR_NIGHT",
    "PCLDY", "PCLDY_NIGHT",
    "CLDY", "CLDY_NIGHT",
    "FOGGY", "FOGGY_NIGHT",
    "DRZL", "DRZL_NIGHT",
    "FZDZ", "FZDZ_NIGHT",
    "RAIN", "RAIN_NIGHT",
    "FZRN", "FZRN_NIGHT",
    "SNOW", "SNOW_NIGHT",
    "SHWR", "SHWR_NIGHT",
    "SNSH", "SNSH_NIGHT",
    "STRM", "STRM_NIGHT",
    "ZZZ",  // unrecognised, exercises the WI_NA fallback
};
