//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by tools/generate-conditions.js.
//     Source: lib/js/weather/conditions.js
//
//     Changes to this file may be lost if the code is regenerated.
//     Edit the source vocabulary and run `npm run gen:conditions` instead.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once

// resolves a condition token to its icon resource, falling back to WI_NA
static uint32_t wx_resource_for_table(const char *condition)
{
    if (!condition)
    {
        return RESOURCE_ID_ICON_WI_NA;
    }

    if (!strcmp(condition, "CLEAR"))
    {
        return RESOURCE_ID_ICON_WI_CLEAR;
    }

    if (!strcmp(condition, "CLEAR_NIGHT"))
    {
        return RESOURCE_ID_ICON_WI_NIGHT_CLEAR;
    }

    if (!strcmp(condition, "PCLDY"))
    {
        return RESOURCE_ID_ICON_WI_PARTLY_CLOUDY;
    }

    if (!strcmp(condition, "PCLDY_NIGHT"))
    {
        return RESOURCE_ID_ICON_WI_NIGHT_PARTLY_CLOUDY;
    }

    if (!strcmp(condition, "CLDY"))
    {
        return RESOURCE_ID_ICON_WI_CLOUDY;
    }

    if (!strcmp(condition, "CLDY_NIGHT"))
    {
        return RESOURCE_ID_ICON_WI_NIGHT_CLOUDY;
    }

    if (!strcmp(condition, "FOGGY"))
    {
        return RESOURCE_ID_ICON_WI_FOG;
    }

    if (!strcmp(condition, "FOGGY_NIGHT"))
    {
        return RESOURCE_ID_ICON_WI_NIGHT_FOG;
    }

    if (!strcmp(condition, "DRZL"))
    {
        return RESOURCE_ID_ICON_WI_DRIZZLE;
    }

    if (!strcmp(condition, "DRZL_NIGHT"))
    {
        return RESOURCE_ID_ICON_WI_NIGHT_DRIZZLE;
    }

    if (!strcmp(condition, "FZDZ"))
    {
        return RESOURCE_ID_ICON_WI_SLEET;
    }

    if (!strcmp(condition, "FZDZ_NIGHT"))
    {
        return RESOURCE_ID_ICON_WI_NIGHT_SLEET;
    }

    if (!strcmp(condition, "RAIN"))
    {
        return RESOURCE_ID_ICON_WI_RAIN;
    }

    if (!strcmp(condition, "RAIN_NIGHT"))
    {
        return RESOURCE_ID_ICON_WI_NIGHT_RAIN;
    }

    if (!strcmp(condition, "FZRN"))
    {
        return RESOURCE_ID_ICON_WI_SLEET;
    }

    if (!strcmp(condition, "FZRN_NIGHT"))
    {
        return RESOURCE_ID_ICON_WI_NIGHT_SLEET;
    }

    if (!strcmp(condition, "SNOW"))
    {
        return RESOURCE_ID_ICON_WI_SNOW;
    }

    if (!strcmp(condition, "SNOW_NIGHT"))
    {
        return RESOURCE_ID_ICON_WI_NIGHT_SNOW;
    }

    if (!strcmp(condition, "SHWR"))
    {
        return RESOURCE_ID_ICON_WI_SHOWERS;
    }

    if (!strcmp(condition, "SHWR_NIGHT"))
    {
        return RESOURCE_ID_ICON_WI_NIGHT_SHOWERS;
    }

    if (!strcmp(condition, "SNSH"))
    {
        return RESOURCE_ID_ICON_WI_SNOW_WIND;
    }

    if (!strcmp(condition, "SNSH_NIGHT"))
    {
        return RESOURCE_ID_ICON_WI_NIGHT_SNOW_WIND;
    }

    if (!strcmp(condition, "STRM"))
    {
        return RESOURCE_ID_ICON_WI_THUNDERSTORM;
    }

    if (!strcmp(condition, "STRM_NIGHT"))
    {
        return RESOURCE_ID_ICON_WI_NIGHT_THUNDERSTORM;
    }

    return RESOURCE_ID_ICON_WI_NA;
}
