//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by lib/tools/build-conditions.ts.
//     Source: lib/ts/weather/conditions.ts
//
//     Changes to this file may be lost if the code is regenerated.
//     Edit the source vocabulary and run `npm run build:conditions` instead.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once

// resolves a condition token to its icon resource, falling back to WEATHER_NOW_NA
static uint32_t wx_resource_for_table(const char *condition)
{
    if (!condition)
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NA;
    }

    if (!strcmp(condition, "CLEAR"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_CLEAR;
    }

    if (!strcmp(condition, "CLEAR_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_CLEAR;
    }

    if (!strcmp(condition, "PCLDY"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_PARTLY_CLOUDY;
    }

    if (!strcmp(condition, "PCLDY_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_PARTLY_CLOUDY;
    }

    if (!strcmp(condition, "CLDY"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_CLOUDY;
    }

    if (!strcmp(condition, "CLDY_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_CLOUDY;
    }

    if (!strcmp(condition, "FOGGY"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_FOG;
    }

    if (!strcmp(condition, "FOGGY_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_FOG;
    }

    if (!strcmp(condition, "DRZL"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_DRIZZLE;
    }

    if (!strcmp(condition, "DRZL_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_DRIZZLE;
    }

    if (!strcmp(condition, "FZDZ"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_SLEET;
    }

    if (!strcmp(condition, "FZDZ_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_SLEET;
    }

    if (!strcmp(condition, "RAIN"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_RAIN;
    }

    if (!strcmp(condition, "RAIN_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_RAIN;
    }

    if (!strcmp(condition, "FZRN"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_SLEET;
    }

    if (!strcmp(condition, "FZRN_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_SLEET;
    }

    if (!strcmp(condition, "SNOW"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_SNOW;
    }

    if (!strcmp(condition, "SNOW_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_SNOW;
    }

    if (!strcmp(condition, "SHWR"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_SHOWERS;
    }

    if (!strcmp(condition, "SHWR_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_SHOWERS;
    }

    if (!strcmp(condition, "SNSH"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_SNOW_WIND;
    }

    if (!strcmp(condition, "SNSH_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_SNOW_WIND;
    }

    if (!strcmp(condition, "STRM"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_THUNDERSTORM;
    }

    if (!strcmp(condition, "STRM_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_THUNDERSTORM;
    }

    return RESOURCE_ID_ICON_WEATHER_NOW_NA;
}
