//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by tools/generate-conditions.js.
//     Source: lib/js/weather/conditions.js
//
//     Changes to this file may be lost if the code is regenerated.
//     Edit the source vocabulary and run `npm run gen:conditions` instead.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once

#include <string.h>

static const char *wx_label_short_for_table(const char *condition)
{
    if (!condition)
    {
        return "UNKNOWN";
    }

    if (!strcmp(condition, "CLEAR"))
    {
        return "CLEAR";
    }

    if (!strcmp(condition, "CLEAR_NIGHT"))
    {
        return "CLEAR";
    }

    if (!strcmp(condition, "PCLDY"))
    {
        return "PCLDY";
    }

    if (!strcmp(condition, "PCLDY_NIGHT"))
    {
        return "PCLDY";
    }

    if (!strcmp(condition, "CLDY"))
    {
        return "CLDY";
    }

    if (!strcmp(condition, "CLDY_NIGHT"))
    {
        return "CLDY";
    }

    if (!strcmp(condition, "FOGGY"))
    {
        return "FOGGY";
    }

    if (!strcmp(condition, "FOGGY_NIGHT"))
    {
        return "FOGGY";
    }

    if (!strcmp(condition, "DRZL"))
    {
        return "DRZL";
    }

    if (!strcmp(condition, "DRZL_NIGHT"))
    {
        return "DRZL";
    }

    if (!strcmp(condition, "FZDZ"))
    {
        return "FZDZ";
    }

    if (!strcmp(condition, "FZDZ_NIGHT"))
    {
        return "FZDZ";
    }

    if (!strcmp(condition, "RAIN"))
    {
        return "RAIN";
    }

    if (!strcmp(condition, "RAIN_NIGHT"))
    {
        return "RAIN";
    }

    if (!strcmp(condition, "FZRN"))
    {
        return "FZRN";
    }

    if (!strcmp(condition, "FZRN_NIGHT"))
    {
        return "FZRN";
    }

    if (!strcmp(condition, "SNOW"))
    {
        return "SNOW";
    }

    if (!strcmp(condition, "SNOW_NIGHT"))
    {
        return "SNOW";
    }

    if (!strcmp(condition, "SHWR"))
    {
        return "SHWR";
    }

    if (!strcmp(condition, "SHWR_NIGHT"))
    {
        return "SHWR";
    }

    if (!strcmp(condition, "SNSH"))
    {
        return "SNSH";
    }

    if (!strcmp(condition, "SNSH_NIGHT"))
    {
        return "SNSH";
    }

    if (!strcmp(condition, "STRM"))
    {
        return "STRM";
    }

    if (!strcmp(condition, "STRM_NIGHT"))
    {
        return "STRM";
    }

    return "UNKNOWN";
}

static const char *wx_label_long_for_table(const char *condition)
{
    if (!condition)
    {
        return "Unknown";
    }

    if (!strcmp(condition, "CLEAR"))
    {
        return "Clear";
    }

    if (!strcmp(condition, "CLEAR_NIGHT"))
    {
        return "Clear";
    }

    if (!strcmp(condition, "PCLDY"))
    {
        return "Partly Cloudy";
    }

    if (!strcmp(condition, "PCLDY_NIGHT"))
    {
        return "Partly Cloudy";
    }

    if (!strcmp(condition, "CLDY"))
    {
        return "Cloudy";
    }

    if (!strcmp(condition, "CLDY_NIGHT"))
    {
        return "Cloudy";
    }

    if (!strcmp(condition, "FOGGY"))
    {
        return "Fog";
    }

    if (!strcmp(condition, "FOGGY_NIGHT"))
    {
        return "Fog";
    }

    if (!strcmp(condition, "DRZL"))
    {
        return "Drizzle";
    }

    if (!strcmp(condition, "DRZL_NIGHT"))
    {
        return "Drizzle";
    }

    if (!strcmp(condition, "FZDZ"))
    {
        return "Freezing Drizzle";
    }

    if (!strcmp(condition, "FZDZ_NIGHT"))
    {
        return "Freezing Drizzle";
    }

    if (!strcmp(condition, "RAIN"))
    {
        return "Rain";
    }

    if (!strcmp(condition, "RAIN_NIGHT"))
    {
        return "Rain";
    }

    if (!strcmp(condition, "FZRN"))
    {
        return "Freezing Rain";
    }

    if (!strcmp(condition, "FZRN_NIGHT"))
    {
        return "Freezing Rain";
    }

    if (!strcmp(condition, "SNOW"))
    {
        return "Snow";
    }

    if (!strcmp(condition, "SNOW_NIGHT"))
    {
        return "Snow";
    }

    if (!strcmp(condition, "SHWR"))
    {
        return "Showers";
    }

    if (!strcmp(condition, "SHWR_NIGHT"))
    {
        return "Showers";
    }

    if (!strcmp(condition, "SNSH"))
    {
        return "Snow Showers";
    }

    if (!strcmp(condition, "SNSH_NIGHT"))
    {
        return "Snow Showers";
    }

    if (!strcmp(condition, "STRM"))
    {
        return "Thunderstorm";
    }

    if (!strcmp(condition, "STRM_NIGHT"))
    {
        return "Thunderstorm";
    }

    return "Unknown";
}
