//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by lib/tools/build-conditions.ts.
//     Source: lib/ts/weather/conditions.ts
//
//     Changes to this file may be lost if the code is regenerated.
//     Edit the source vocabulary and run `npm run build:conditions` instead.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once

#include <string.h>

static const char *wx_label_short_for_table(const char *condition)
{
    if (!condition)
    {
        return "UNKNOWN";
    }

    // a night token reuses its day label, so drop a trailing "_NIGHT" before the lookup
    char base[24];
    size_t len = strlen(condition);
    if (len > 6 && !strcmp(condition + len - 6, "_NIGHT"))
    {
        len -= 6;
    }
    if (len >= sizeof(base))
    {
        len = sizeof(base) - 1;
    }
    memcpy(base, condition, len);
    base[len] = '\0';

    if (!strcmp(base, "CLEAR"))
    {
        return "CLEAR";
    }

    if (!strcmp(base, "PCLDY"))
    {
        return "PCLDY";
    }

    if (!strcmp(base, "CLDY"))
    {
        return "CLDY";
    }

    if (!strcmp(base, "FOGGY"))
    {
        return "FOGGY";
    }

    if (!strcmp(base, "DRZL"))
    {
        return "DRZL";
    }

    if (!strcmp(base, "FZDZ"))
    {
        return "FZDZ";
    }

    if (!strcmp(base, "RAIN"))
    {
        return "RAIN";
    }

    if (!strcmp(base, "FZRN"))
    {
        return "FZRN";
    }

    if (!strcmp(base, "SNOW"))
    {
        return "SNOW";
    }

    if (!strcmp(base, "SHWR"))
    {
        return "SHWR";
    }

    if (!strcmp(base, "SNSH"))
    {
        return "SNSH";
    }

    if (!strcmp(base, "STRM"))
    {
        return "STRM";
    }

    return "UNKNOWN";
}

static const char *wx_label_long_for_table(const char *condition)
{
    if (!condition)
    {
        return "Unknown";
    }

    // a night token reuses its day label, so drop a trailing "_NIGHT" before the lookup
    char base[24];
    size_t len = strlen(condition);
    if (len > 6 && !strcmp(condition + len - 6, "_NIGHT"))
    {
        len -= 6;
    }
    if (len >= sizeof(base))
    {
        len = sizeof(base) - 1;
    }
    memcpy(base, condition, len);
    base[len] = '\0';

    if (!strcmp(base, "CLEAR"))
    {
        return "Clear";
    }

    if (!strcmp(base, "PCLDY"))
    {
        return "Partly Cloudy";
    }

    if (!strcmp(base, "CLDY"))
    {
        return "Cloudy";
    }

    if (!strcmp(base, "FOGGY"))
    {
        return "Fog";
    }

    if (!strcmp(base, "DRZL"))
    {
        return "Drizzle";
    }

    if (!strcmp(base, "FZDZ"))
    {
        return "Freezing Drizzle";
    }

    if (!strcmp(base, "RAIN"))
    {
        return "Rain";
    }

    if (!strcmp(base, "FZRN"))
    {
        return "Freezing Rain";
    }

    if (!strcmp(base, "SNOW"))
    {
        return "Snow";
    }

    if (!strcmp(base, "SHWR"))
    {
        return "Showers";
    }

    if (!strcmp(base, "SNSH"))
    {
        return "Snow Showers";
    }

    if (!strcmp(base, "STRM"))
    {
        return "Thunderstorm";
    }

    return "Unknown";
}
