/**
 * Base64-encodes the cropped panel PNGs in resources/thumbnails/ into the JS asset the
 * Clay layout and theme builders read, so the palette and blocks show the real module
 * instead of an emoji. The builders run in a sandboxed config webview that cannot reach
 * local resource files, so the images have to travel inline as data URLs.
 *
 * Input:  resources/thumbnails/<slug>-<size>.png
 * Output: src/pkjs/clay/module-thumbnails.g.js  ->  module.exports = { label: { size: dataUrl } }
 *
 * The slug -> label mapping is not kept here: it comes from module-meta.ts, which is already
 * the label-keyed registry the builders read (each row's `slug` is the filename stem). Keyed by
 * label so the builders look a thumbnail up by name, the same resilient way they map icons and
 * colours, rather than a numeric id that could drift. Row order follows module-meta.ts.
 *
 * Run: npm run gen:thumbnails   (reports encoded / missing / stray)
 */
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { faceDir } from '../../../../../tools/faces.ts';
import type { ModuleMeta } from '../../pkjs/types.ts';
// the builders read the emitted asset, so generate to the type they consume
import type { Thumbs } from '../../pkjs/clay/builder/ts/types.ts';

// this generator lives in the family core, so every path it touches hangs off the face it is
// handed: the screenshots, that face's module list, and the asset it writes
const requireMeta = createRequire(import.meta.url);

function shotsDir(face: string): string {
  return path.join(faceDir(face), 'resources', 'thumbnails');
}

export function outFile(face: string): string {
  return path.join(faceDir(face), 'src', 'pkjs', 'clay', 'module-thumbnails.g.js');
}

/** A face's own module list, loaded by path because which face it is is only known at runtime. */
function metaFor(face: string): Record<string, ModuleMeta> {
  return requireMeta(path.join(faceDir(face), 'src', 'pkjs', 'clay', 'module-meta.ts')).default;
}

const VALID_SIZES = ['1x2', '2x2', '1x4', '2x4'];

/**
 * The registry as module-meta.ts exports it, keyed by display label. Narrowed to the one
 * field this reads, so the row type stays the real one but a caller only owes us a slug.
 */
type ModuleMetaRegistry = Record<string, Pick<ModuleMeta, 'slug'>>;

/** slug -> which module owns it and where its row sorts. */
type SlugIndex = Record<string, { label: string; order: number }>;

/** A PNG that matched a known slug and a real size. */
type Shot = { file: string; slug: string; label: string; order: number; size: string };

/**
 * Indexes the label-keyed registry by slug, keeping each row's position as its
 * sort order so the emitted file follows module-meta.ts.
 */
export function indexBySlug(meta: ModuleMetaRegistry): SlugIndex {
  const bySlug: SlugIndex = {};
  Object.keys(meta).forEach((label, index) => {
    bySlug[meta[label].slug] = { label: label, order: index };
  });
  return bySlug;
}

/**
 * Splits the PNG names into the ones that match a known slug and a real size and
 * the strays. A name is <slug>-<size>, split on the last dash so a slug can hold
 * its own dashes.
 */
export function classify(files: string[], bySlug: SlugIndex): { shots: Shot[]; stray: string[] } {
  const shots: Shot[] = [];
  const stray: string[] = [];

  files.forEach((file) => {
    const base = file.replace(/\.png$/i, '');
    const dash = base.lastIndexOf('-');
    const slug = dash > 0 ? base.slice(0, dash) : base;
    const size = dash > 0 ? base.slice(dash + 1) : '';
    const entry = bySlug[slug];

    if (!entry || VALID_SIZES.indexOf(size) === -1) {
      stray.push(file);
      return;
    }

    shots.push({ file: file, slug: slug, label: entry.label, order: entry.order, size: size });
  });

  return { shots: shots, stray: stray };
}

/** Renders the asset source, rows sorted by module order so the file is stable across runs. */
export function buildSource(thumbs: Thumbs, order: Record<string, number>): string {
  const lines = [
    '// generated by src/tools/thumbnails/generate-thumbnails.ts - do not edit by hand',
    'module.exports = {',
  ];
  Object.keys(thumbs)
    .sort((a, b) => order[a] - order[b])
    .forEach((label) => {
      const sizes = thumbs[label];
      const parts = Object.keys(sizes)
        .sort()
        .map((size) => JSON.stringify(size) + ': ' + JSON.stringify(sizes[size]));
      lines.push('  ' + JSON.stringify(label) + ': { ' + parts.join(', ') + ' },');
    });
  lines.push('};', '');
  return lines.join('\n');
}

/** The registry slugs that no PNG covered, so a new module with no shot gets reported. */
export function missingSlugs(meta: ModuleMetaRegistry, seen: Record<string, boolean>): string[] {
  return Object.keys(meta)
    .filter((label) => !seen[meta[label].slug])
    .map((label) => meta[label].slug);
}

/** What one run would produce: the asset source plus what it found on the way. */
export interface Built {
  source: string;
  modules: number;
  panels: number;
  missing: string[];
  stray: string[];
}

/**
 * Reads the PNGs and encodes them inline, without touching the output.
 *
 * Split from build so the spec can ask what the generator *would* write and compare it to
 * the committed copy, the way generate-components.ts does.
 */
export function buildFromShots(face: string): Built {
  const moduleMeta = metaFor(face);
  const bySlug = indexBySlug(moduleMeta);
  const dir = shotsDir(face);

  const files = fs.existsSync(dir)
    ? fs.readdirSync(dir).filter((name) => name.toLowerCase().endsWith('.png'))
    : [];

  const { shots, stray } = classify(files, bySlug);

  const thumbs: Thumbs = {};
  const order: Record<string, number> = {};
  const seen: Record<string, boolean> = {};

  shots.forEach((shot) => {
    const data = fs.readFileSync(path.join(dir, shot.file)).toString('base64');
    if (!thumbs[shot.label]) {
      thumbs[shot.label] = {};
    }
    thumbs[shot.label][shot.size] = 'data:image/png;base64,' + data;
    order[shot.label] = shot.order;
    seen[shot.slug] = true;
  });

  return {
    source: buildSource(thumbs, order),
    modules: Object.keys(thumbs).length,
    panels: files.length - stray.length,
    missing: missingSlugs(moduleMeta, seen),
    stray: stray,
  };
}

/** Writes the asset, once the run is known good. Throws rather than ship a half-right one. */
export function build(face: string): void {
  const built = buildFromShots(face);

  // check before writing. a stray png names a slug no module claims, and a missing one
  // leaves a module with no preview. writing first would clobber the good committed asset
  // with a regressed one on the way to throwing, and nothing would force a checkout
  if (built.stray.length) {
    throw new Error(`stray png with no module (${built.stray.length}): ${built.stray.join(', ')}`);
  }
  if (built.missing.length) {
    throw new Error(`module with no png (${built.missing.length}): ${built.missing.join(', ')}`);
  }

  const out = outFile(face);
  fs.writeFileSync(out, built.source);

  const bytes = fs.statSync(out).size;
  console.log('wrote ' + out + ' (' + Math.round(bytes / 1024) + ' KB)');
  console.log('encoded: ' + built.modules + ' modules, ' + built.panels + ' panels');
}

if (import.meta.main) {
  const face = process.argv[2];
  if (!face) {
    throw new Error('usage: generate-thumbnails.ts <face>');
  }
  build(face);
}
