#!/usr/bin/env python3
"""Generate the value-font left-bearing table from the Teko TTF.

Left-aligned numeric/text values start at a fixed box, but each glyph carries its own
left-side-bearing, so the first character's visible ink lands 0-2px in depending on which
glyph it is (a "1" sits tighter than an "8"). This reads the real left-side-bearings out
of the font and bakes a per-glyph pixel offset, so the draw code can shift each value to
land its first glyph's ink at the same inset every time.

Pebble renders a glyph's ink at round(lsb * size / unitsPerEm) from the pen, which was
verified pixel-exact against emulator screenshots for both digits and letters.

Writes the family core's draw/value_bearing.g.h. Rerun after changing the value font.

    src/tools/fonts/generate-bearing.py
"""
import os
import struct

HERE = os.path.dirname(os.path.abspath(__file__))
FACE = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
TTF = os.path.join(FACE, "resources", "fonts", "Teko-SemiBold.ttf")
# the table is read by the shared panel drawing, so it lands in the family core
OUT = os.path.join(os.path.dirname(FACE), "core", "c", "draw", "value_bearing.g.h")

# the left-aligned value fonts (font slot, render px). the big 34 and the clock
# sizes are centre-aligned or never lead a stat value, so they are left out
FONTS = [("FONT_TEKO_26", 26), ("FONT_TEKO_24", 24), ("FONT_TEKO_22", 22)]

FIRST, LAST = 32, 126  # printable ASCII


def load_ttf(path):
    data = open(path, "rb").read()

    def u16(o):
        return struct.unpack(">H", data[o:o + 2])[0]

    def s16(o):
        return struct.unpack(">h", data[o:o + 2])[0]

    def u32(o):
        return struct.unpack(">I", data[o:o + 4])[0]

    tables = {}
    for i in range(u16(4)):
        o = 12 + i * 16
        tables[data[o:o + 4].decode("latin1")] = u32(o + 8)

    units = u16(tables["head"] + 18)
    num_hmetrics = u16(tables["hhea"] + 34)
    cmap = tables["cmap"]
    # take the last cmap subtable (a BMP format-4 unicode map for this font)
    sub = cmap + u32(cmap + 4 + (u16(cmap + 2) - 1) * 8 + 4)
    hmtx = tables["hmtx"]

    def glyph_id(ch):
        seg2 = u16(sub + 6)
        seg_count = seg2 // 2
        end_o = sub + 14
        start_o = end_o + seg2 + 2
        delta_o = start_o + seg2
        range_o = delta_o + seg2
        code = ord(ch)
        for s in range(seg_count):
            if code <= u16(end_o + s * 2):
                start = u16(start_o + s * 2)
                if code < start:
                    return 0
                delta = u16(delta_o + s * 2)
                range_off = u16(range_o + s * 2)
                if range_off == 0:
                    return (code + delta) & 0xFFFF
                gid = u16(range_o + s * 2 + range_off + (code - start) * 2)
                return 0 if gid == 0 else (gid + delta) & 0xFFFF
        return 0

    def lsb(ch):
        gid = glyph_id(ch)
        if gid < num_hmetrics:
            return s16(hmtx + gid * 4 + 2)
        return s16(hmtx + num_hmetrics * 4 + (gid - num_hmetrics) * 2)

    return units, lsb


def main():
    units, lsb = load_ttf(TTF)

    lines = []
    lines.append("// GENERATED by src/tools/fonts/generate-bearing.py from resources/fonts/Teko-SemiBold.ttf")
    lines.append("// Do not edit by hand. Rerun the generator after changing the value font.")
    lines.append("//")
    lines.append("// Per-glyph left ink offset (px) for the left-aligned Teko value fonts, so the draw")
    lines.append("// code can shift a value to land its first glyph's ink at the same inset no matter")
    lines.append("// which character leads. = round(lsb * size / unitsPerEm), verified against the")
    lines.append("// emulator. Indexed by (char - 32) over printable ASCII. See gh_value_left.")
    lines.append("#pragma once")
    lines.append("#include \"draw/fonts.h\"")
    lines.append("")

    for name, size in FONTS:
        vals = []
        for code in range(FIRST, LAST + 1):
            off = round(lsb(chr(code)) * size / units)
            vals.append(off)
        arr = ", ".join(str(v) for v in vals)
        lines.append(f"// {name} ({size}px)")
        lines.append(f"static const int8_t s_ink_off_{size}[{LAST - FIRST + 1}] = {{ {arr} }};")
        lines.append("")

    lines.append("// px to add to a value's left pad so its first glyph's ink sits at the target inset,")
    lines.append("// which is 1px in to clear the border (matching EDGE_PAD, border-independent so the")
    lines.append("// value does not shift when the border is toggled). Returns 0 for fonts this table")
    lines.append("// does not cover (leaves them untouched).")
    lines.append("static inline int value_bearing_fix(char first, FontId font)")
    lines.append("{")
    lines.append("    const int8_t *table;")
    lines.append("    switch (font)")
    lines.append("    {")
    for name, size in FONTS:
        lines.append(f"        case {name}: table = s_ink_off_{size}; break;")
    lines.append("        default: return 0;")
    lines.append("    }")
    lines.append(f"    unsigned index = (unsigned char)first - {FIRST}u;")
    lines.append(f"    if (index >= {LAST - FIRST + 1}u) {{ return 0; }}")
    lines.append("    return 1 - table[index];")
    lines.append("}")
    lines.append("")

    open(OUT, "w", newline="\n").write("\n".join(lines))
    print(f"wrote {OUT} ({LAST - FIRST + 1} glyphs x {len(FONTS)} sizes)")


if __name__ == "__main__":
    main()
