/**
 * Specs for the C weather-icon table generator.
 *
 * buildIconsTable is a pure codegen transform: vocabulary in, C source out.
 * A drifted branch or wrong fallback ships a watchface that compiles to the
 * wrong icon (or fails to compile), so the generated shape is pinned here.
 */

import { describe, test, expect } from 'vitest';
import { buildIconsTable, buildLabelsTable, buildDevConditionsTable } from './generate-conditions.js';
import vocabulary from '../lib/js/weather/conditions.js';

describe('buildIconsTable', () => {
  /** A missing null guard would dereference a null condition string on the watch and crash. */
  test('returns the fallback resource when the condition pointer is null', () => {
    const source = buildIconsTable({
      fallback: 'WI_NA',
      conditions: [{ token: 'RAIN', resource: 'WI_RAIN' }]
    });

    expect(source).toContain('    if (!condition)\n    {\n        return RESOURCE_ID_ICON_WI_NA;\n    }');
  });

  /** A token mapped to the wrong resource silently shows the wrong icon, so the exact branch is pinned. */
  test('emits a strcmp branch mapping each token to its icon resource', () => {
    const source = buildIconsTable({
      fallback: 'WI_NA',
      conditions: [{ token: 'RAIN', resource: 'WI_RAIN' }]
    });

    expect(source).toContain(
      '    if (!strcmp(condition, "RAIN"))\n    {\n        return RESOURCE_ID_ICON_WI_RAIN;\n    }'
    );
  });

  /** Two tokens sharing one glyph (FZDZ/FZRN -> WI_SLEET) must both still get their own branch. */
  test('emits a separate branch for each token even when they share a resource', () => {
    const source = buildIconsTable({
      fallback: 'WI_NA',
      conditions: [
        { token: 'FZDZ', resource: 'WI_SLEET' },
        { token: 'FZRN', resource: 'WI_SLEET' }
      ]
    });

    expect(source).toContain('!strcmp(condition, "FZDZ")');
    expect(source).toContain('!strcmp(condition, "FZRN")');
    expect(source.match(/RESOURCE_ID_ICON_WI_SLEET;/g)).toHaveLength(2);
  });

  /** The final unmatched return must use the configured fallback, not a hard-coded one. */
  test('ends the lookup with the configured fallback resource', () => {
    const source = buildIconsTable({
      fallback: 'WI_CUSTOM',
      conditions: [{ token: 'RAIN', resource: 'WI_RAIN' }]
    });

    expect(source.trimEnd().endsWith('    return RESOURCE_ID_ICON_WI_CUSTOM;\n}')).toBe(true);
  });

  /** The output is a header that gets #included, so it needs the include guard and the do-not-edit banner. */
  test('emits a #pragma once header and the auto-generated banner', () => {
    const source = buildIconsTable({
      fallback: 'WI_NA',
      conditions: [{ token: 'RAIN', resource: 'WI_RAIN' }]
    });

    expect(source).toContain('#pragma once');
    expect(source).toContain('// <auto-generated>');
  });

  /** Every token in the shipped vocabulary must reach the generated table - a dropped one renders WI_NA. */
  test('covers every condition in the real vocabulary', () => {
    const source = buildIconsTable(vocabulary);

    for (const { token, resource } of vocabulary.conditions) {
      expect(source).toContain(`!strcmp(condition, "${token}")`);
      expect(source).toContain(`return RESOURCE_ID_ICON_${resource};`);
    }
  });

  /** The wire carries "<token>_NIGHT" after dark; without the generated night
   *  branch the watch would fall through to WI_NA and lose the moon glyph. */
  test('emits a _NIGHT branch mapping to the night resource for night-capable rows', () => {
    const source = buildIconsTable({
      fallback: { resource: 'WI_NA' },
      conditions: [{ token: 'RAIN', resource: 'WI_RAIN', nightResource: 'WI_NIGHT_RAIN' }]
    });

    expect(source).toContain(
      '    if (!strcmp(condition, "RAIN_NIGHT"))\n    {\n        return RESOURCE_ID_ICON_WI_NIGHT_RAIN;\n    }'
    );
  });

  /** A row with no nightResource must not emit a phantom _NIGHT branch. */
  test('omits the _NIGHT branch when a row has no night resource', () => {
    const source = buildIconsTable({
      fallback: { resource: 'WI_NA' },
      conditions: [{ token: 'DUST', resource: 'WI_DUST' }]
    });

    expect(source).not.toContain('DUST_NIGHT');
  });

  /** The fallback is now an object; the generator must read fallback.resource, not the object itself. */
  test('accepts an object fallback and uses its resource', () => {
    const source = buildIconsTable({
      fallback: { resource: 'WI_NA', labelShort: 'UNKNOWN', labelLong: 'Unknown' },
      conditions: [{ token: 'RAIN', resource: 'WI_RAIN' }]
    });

    expect(source.trimEnd().endsWith('    return RESOURCE_ID_ICON_WI_NA;\n}')).toBe(true);
  });
});

describe('buildLabelsTable', () => {
  /** A roomy face shows labelLong; a wrong/dropped mapping renders "Unknown" instead of "Partly Cloudy". */
  test('maps each token to its short and long label', () => {
    const source = buildLabelsTable({
      fallback: { resource: 'WI_NA', labelShort: 'UNKNOWN', labelLong: 'Unknown' },
      conditions: [{ token: 'PCLDY', resource: 'WI_PARTLY_CLOUDY', labelShort: 'PCLDY', labelLong: 'Partly Cloudy' }]
    });

    expect(source).toContain('    if (!strcmp(condition, "PCLDY"))\n    {\n        return "PCLDY";\n    }');
    expect(source).toContain('    if (!strcmp(condition, "PCLDY"))\n    {\n        return "Partly Cloudy";\n    }');
  });

  /** The C side never strips the night marker, so a night token must resolve to the
   *  same label as its day token instead of falling through to the fallback. */
  test('maps a night token to the same labels as its day token', () => {
    const source = buildLabelsTable({
      fallback: { resource: 'WI_NA', labelShort: 'UNKNOWN', labelLong: 'Unknown' },
      conditions: [{ token: 'RAIN', resource: 'WI_RAIN', nightResource: 'WI_NIGHT_RAIN', labelShort: 'RAIN', labelLong: 'Rain' }]
    });

    expect(source).toContain('!strcmp(condition, "RAIN_NIGHT")');
    expect(source.match(/return "Rain";/g)).toHaveLength(2); // day + night branch
  });

  /** Both lookup functions must fall back to the configured labels for an unknown/null token. */
  test('ends each function with the configured fallback label', () => {
    const source = buildLabelsTable({
      fallback: { resource: 'WI_NA', labelShort: 'UNKNOWN', labelLong: 'Unknown' },
      conditions: [{ token: 'RAIN', resource: 'WI_RAIN', labelShort: 'RAIN', labelLong: 'Rain' }]
    });

    expect(source).toContain('const char *wx_label_short_for_table');
    expect(source).toContain('const char *wx_label_long_for_table');
    expect(source).toContain('return "UNKNOWN";');
    expect(source).toContain('return "Unknown";');
  });

  /** Every shipped condition must reach both label tables - a dropped one renders the fallback. */
  test('covers every condition in the real vocabulary', () => {
    const source = buildLabelsTable(vocabulary);

    for (const { token, labelShort, labelLong } of vocabulary.conditions) {
      expect(source).toContain(`!strcmp(condition, "${token}")`);
      expect(source).toContain(`return "${labelShort}";`);
      expect(source).toContain(`return "${labelLong}";`);
    }
  });
});

describe('buildDevConditionsTable', () => {
  /** The icon walk taps this array in order, so a night form must sit right after its day
   *  form or the two never appear side by side for comparison. */
  test('emits each night token adjacent to its day token', () => {
    const source = buildDevConditionsTable({
      conditions: [{ token: 'RAIN', resource: 'WI_RAIN', nightResource: 'WI_NIGHT_RAIN' }]
    });

    expect(source).toContain('"RAIN", "RAIN_NIGHT",');
  });

  /** A day-only condition has no night form, so it must emit a single token rather than a
   *  bogus "<token>_NIGHT" the icon table would resolve to the fallback. */
  test('emits a lone token for a day-only condition', () => {
    const source = buildDevConditionsTable({
      conditions: [{ token: 'CLEAR', resource: 'WI_CLEAR' }]
    });

    expect(source).toContain('    "CLEAR",\n');
    expect(source).not.toContain('CLEAR_NIGHT');
  });

  /** The walk must end on an unrecognised token so the NA fallback icon gets exercised too. */
  test('ends with a bogus token for the NA fallback', () => {
    const source = buildDevConditionsTable({
      conditions: [{ token: 'CLEAR', resource: 'WI_CLEAR' }]
    });

    expect(source).toContain('"ZZZ"');
    expect(source).toContain('static const char *const wx_dev_condition_tokens[]');
  });

  /** The icon walk's coverage is only complete if every shipped token (day and night) is in
   *  the list, so a vocabulary addition can never silently skip an icon. */
  test('covers every token in the real vocabulary', () => {
    const source = buildDevConditionsTable(vocabulary);

    for (const { token, nightResource } of vocabulary.conditions) {
      expect(source).toContain(`"${token}"`);
      if (nightResource) {
        expect(source).toContain(`"${token}_NIGHT"`);
      }
    }
  });
});
