/**
 * Specs for the C weather-icon table generator.
 *
 * buildIconsTable is a pure codegen transform: vocabulary in, C source out.
 * A drifted branch or wrong fallback ships a watchface that compiles to the
 * wrong icon (or fails to compile), so the generated shape is pinned here.
 */

import { describe, test, expect } from 'vitest';
import { buildIconsTable } from './generate-conditions.js';
import vocabulary from '../lib/js/weather/conditions.js';

describe('buildIconsTable', () => {
  /** A missing null guard would dereference a null condition string on the watch and crash. */
  test('returns the fallback resource when the condition pointer is null', () => {
    const source = buildIconsTable({
      fallback: 'WI_NA',
      conditions: [{ token: 'RAIN', resource: 'WI_RAIN' }]
    });

    expect(source).toContain('    if (!condition)\n    {\n        return RESOURCE_ID_ICON_WI_NA;\n    }');
  });

  /** A token mapped to the wrong resource silently shows the wrong icon, so the exact branch is pinned. */
  test('emits a strcmp branch mapping each token to its icon resource', () => {
    const source = buildIconsTable({
      fallback: 'WI_NA',
      conditions: [{ token: 'RAIN', resource: 'WI_RAIN' }]
    });

    expect(source).toContain(
      '    if (!strcmp(condition, "RAIN"))\n    {\n        return RESOURCE_ID_ICON_WI_RAIN;\n    }'
    );
  });

  /** Two tokens sharing one glyph (FZDZ/FZRN -> WI_SLEET) must both still get their own branch. */
  test('emits a separate branch for each token even when they share a resource', () => {
    const source = buildIconsTable({
      fallback: 'WI_NA',
      conditions: [
        { token: 'FZDZ', resource: 'WI_SLEET' },
        { token: 'FZRN', resource: 'WI_SLEET' }
      ]
    });

    expect(source).toContain('!strcmp(condition, "FZDZ")');
    expect(source).toContain('!strcmp(condition, "FZRN")');
    expect(source.match(/RESOURCE_ID_ICON_WI_SLEET;/g)).toHaveLength(2);
  });

  /** The final unmatched return must use the configured fallback, not a hard-coded one. */
  test('ends the lookup with the configured fallback resource', () => {
    const source = buildIconsTable({
      fallback: 'WI_CUSTOM',
      conditions: [{ token: 'RAIN', resource: 'WI_RAIN' }]
    });

    expect(source.trimEnd().endsWith('    return RESOURCE_ID_ICON_WI_CUSTOM;\n}')).toBe(true);
  });

  /** The output is a header that gets #included, so it needs the include guard and the do-not-edit banner. */
  test('emits a #pragma once header and the auto-generated banner', () => {
    const source = buildIconsTable({
      fallback: 'WI_NA',
      conditions: [{ token: 'RAIN', resource: 'WI_RAIN' }]
    });

    expect(source).toContain('#pragma once');
    expect(source).toContain('// <auto-generated>');
  });

  /** Every token in the shipped vocabulary must reach the generated table - a dropped one renders WI_NA. */
  test('covers every condition in the real vocabulary', () => {
    const source = buildIconsTable(vocabulary);

    for (const { token, resource } of vocabulary.conditions) {
      expect(source).toContain(`!strcmp(condition, "${token}")`);
      expect(source).toContain(`return RESOURCE_ID_ICON_${resource};`);
    }
  });
});
