/**
 * Specs for the C weather-icon table generator.
 *
 * buildIconsTable is a pure codegen transform: vocabulary in, C source out.
 * A drifted branch or wrong fallback ships a watchface that compiles to the
 * wrong icon (or fails to compile), so the generated shape is pinned here.
 */

import { describe, test, expect } from 'vitest';
import { buildIconsTable, buildIconCodesTable, buildLabelsTable } from './build-conditions';
import vocabulary from '../ts/weather/conditions.ts';
import type { ConditionEntry, ConditionFallback } from '../ts/weather/conditions.ts';

/** The fallback shape conditions.ts really exports: a resource plus both labels. */
const FALLBACK: ConditionFallback = { resource: 'WI_NA', labelShort: 'UNKNOWN', labelLong: 'Unknown' };

/** A fallback on a named resource, for the cases that pin which resource is used. */
function fallbackOf(resource: string): ConditionFallback {
  return { resource: resource, labelShort: 'UNKNOWN', labelLong: 'Unknown' };
}

/** One row, labels defaulted so an icon case only spells out the fields it is about. */
function row(token: string, resource: string, nightResource?: string): ConditionEntry {
  return { token: token, resource: resource, nightResource: nightResource, labelShort: token, labelLong: token };
}

describe('buildIconsTable', () => {
  /** A missing null guard would dereference a null condition string on the watch and crash. */
  test('returns the fallback resource when the condition pointer is null', () => {
    const source = buildIconsTable({
      fallback: FALLBACK,
      conditions: [row('RAIN', 'WI_RAIN')],
    });

    expect(source).toContain('    if (!condition)\n    {\n        return RESOURCE_ID_ICON_WI_NA;\n    }');
  });

  /** A token mapped to the wrong resource silently shows the wrong icon, so the exact branch is pinned. */
  test('emits a strcmp branch mapping each token to its icon resource', () => {
    const source = buildIconsTable({
      fallback: FALLBACK,
      conditions: [row('RAIN', 'WI_RAIN')],
    });

    expect(source).toContain(
      '    if (!strcmp(condition, "RAIN"))\n    {\n        return RESOURCE_ID_ICON_WI_RAIN;\n    }'
    );
  });

  /** Two tokens sharing one glyph (FZDZ/FZRN -> WI_SLEET) must both still get their own branch. */
  test('emits a separate branch for each token even when they share a resource', () => {
    const source = buildIconsTable({
      fallback: FALLBACK,
      conditions: [
        row('FZDZ', 'WI_SLEET'),
        row('FZRN', 'WI_SLEET'),
      ],
    });

    expect(source).toContain('!strcmp(condition, "FZDZ")');
    expect(source).toContain('!strcmp(condition, "FZRN")');
    expect(source.match(/RESOURCE_ID_ICON_WI_SLEET;/g)).toHaveLength(2);
  });

  /** The final unmatched return must use the configured fallback, not a hard-coded one. */
  test('ends the lookup with the configured fallback resource', () => {
    const source = buildIconsTable({
      fallback: fallbackOf('WI_CUSTOM'),
      conditions: [row('RAIN', 'WI_RAIN')],
    });

    expect(source.trimEnd().endsWith('    return RESOURCE_ID_ICON_WI_CUSTOM;\n}')).toBe(true);
  });

  /** The output is a header that gets #included, so it needs the include guard and the do-not-edit banner. */
  test('emits a #pragma once header and the auto-generated banner', () => {
    const source = buildIconsTable({
      fallback: FALLBACK,
      conditions: [row('RAIN', 'WI_RAIN')],
    });

    expect(source).toContain('#pragma once');
    expect(source).toContain('// <auto-generated>');
  });

  /** Every token in the shipped vocabulary must reach the generated table - a dropped one renders WI_NA. */
  test('covers every condition in the real vocabulary', () => {
    const source = buildIconsTable(vocabulary);

    for (const { token, resource } of vocabulary.conditions) {
      expect(source).toContain(`!strcmp(condition, "${token}")`);
      expect(source).toContain(`return RESOURCE_ID_ICON_${resource};`);
    }
  });

  /** The wire carries "<token>_NIGHT" after dark. Without the generated night
   *  branch the watch would fall through to WI_NA and lose the moon glyph. */
  test('emits a _NIGHT branch mapping to the night resource for night-capable rows', () => {
    const source = buildIconsTable({
      fallback: FALLBACK,
      conditions: [row('RAIN', 'WI_RAIN', 'WI_NIGHT_RAIN')],
    });

    expect(source).toContain(
      '    if (!strcmp(condition, "RAIN_NIGHT"))\n    {\n        return RESOURCE_ID_ICON_WI_NIGHT_RAIN;\n    }'
    );
  });

  /** A row with no nightResource must not emit a phantom _NIGHT branch. */
  test('omits the _NIGHT branch when a row has no night resource', () => {
    const source = buildIconsTable({
      fallback: FALLBACK,
      conditions: [row('DUST', 'WI_DUST')],
    });

    expect(source).not.toContain('DUST_NIGHT');
  });

});

describe('codeFor', () => {
  /** The forecast wire code is the array index, so a drift here draws the wrong icon on every column. */
  test('returns the array index of a known token', () => {
    const index = vocabulary.codeFor('CLDY');

    expect(index).toBe(vocabulary.conditions.findIndex((entry) => entry.token === 'CLDY'));
  });

  /** The forecast shows day glyphs, so a night token must map to the same code as its day form. */
  test('strips the night marker before looking up the code', () => {
    const result = vocabulary.codeFor('RAIN_NIGHT');

    expect(result).toBe(vocabulary.codeFor('RAIN'));
  });

  /** An unknown or empty token must land on UNKNOWN_CODE so the watch draws WI_NA, not a random icon. */
  test('returns UNKNOWN_CODE for an unrecognised or empty token', () => {
    expect(vocabulary.codeFor('ZZZ')).toBe(vocabulary.UNKNOWN_CODE);
    expect(vocabulary.codeFor('')).toBe(vocabulary.UNKNOWN_CODE);
  });
});

describe('buildIconCodesTable', () => {
  /** The switch index is the wire code, so a case mapped to the wrong resource draws the wrong sky. */
  test('emits a case mapping each code to its day icon resource', () => {
    const source = buildIconCodesTable({
      fallback: FALLBACK,
      conditions: [row('CLEAR', 'WI_CLEAR'), row('RAIN', 'WI_RAIN')],
    });

    expect(source).toContain('    case 0: return RESOURCE_ID_ICON_WI_CLEAR;');
    expect(source).toContain('    case 1: return RESOURCE_ID_ICON_WI_RAIN;');
  });

  /** A night-capable row must branch on the night bit, else a dark hour still draws the day sun. */
  test('emits a night ternary picking the night resource for a night-capable row', () => {
    const source = buildIconCodesTable({
      fallback: FALLBACK,
      conditions: [row('CLEAR', 'WI_CLEAR', 'WI_NIGHT_CLEAR')],
    });

    expect(source).toContain('    case 0: return night ? RESOURCE_ID_ICON_WI_NIGHT_CLEAR : RESOURCE_ID_ICON_WI_CLEAR;');
  });

  /** The switch must mask off the night bit or the night codes (128+) run off the end to WI_NA. */
  test('decodes the night bit before switching on the code', () => {
    const source = buildIconCodesTable({ fallback: FALLBACK, conditions: [row('CLEAR', 'WI_CLEAR')] });

    expect(source).toContain('bool night = (code & WX_FORECAST_NIGHT_BIT) != 0;');
    expect(source).toContain('switch (code & ~WX_FORECAST_NIGHT_BIT)');
  });

  /** An out-of-range or UNKNOWN_CODE byte must fall back to WI_NA instead of running off the switch. */
  test('defaults unknown codes to the configured fallback resource', () => {
    const source = buildIconCodesTable({
      fallback: FALLBACK,
      conditions: [row('CLEAR', 'WI_CLEAR')],
    });

    expect(source).toContain('    default: return RESOURCE_ID_ICON_WI_NA;');
  });

  /** The generated case index must equal codeFor for the same row or the C and JS sides disagree. */
  test('numbers cases so they line up with codeFor over the real vocabulary', () => {
    const source = buildIconCodesTable(vocabulary);

    vocabulary.conditions.forEach((entry, index) => {
      expect(vocabulary.codeFor(entry.token)).toBe(index);
      // every real condition ships a night glyph so the case is the night ternary
      expect(source).toContain(`    case ${index}: return night ? RESOURCE_ID_ICON_${entry.nightResource} : RESOURCE_ID_ICON_${entry.resource};`);
    });
  });
});

describe('buildLabelsTable', () => {
  /** A roomy face shows labelLong. A wrong/dropped mapping renders "Unknown" instead of "Partly Cloudy". */
  test('maps each token to its short and long label', () => {
    const source = buildLabelsTable({
      fallback: FALLBACK,
      conditions: [{ token: 'PCLDY', resource: 'WI_PARTLY_CLOUDY', labelShort: 'PCLDY', labelLong: 'Partly Cloudy' }],
    });

    expect(source).toContain('    if (!strcmp(base, "PCLDY"))\n    {\n        return "PCLDY";\n    }');
    expect(source).toContain('    if (!strcmp(base, "PCLDY"))\n    {\n        return "Partly Cloudy";\n    }');
  });

  /** A night token resolves to its day label by stripping a trailing "_NIGHT" before the
   *  lookup (not a separate branch), so the table stays half the size. */
  test('strips a night token to its day label instead of emitting a separate branch', () => {
    const source = buildLabelsTable({
      fallback: FALLBACK,
      conditions: [{ token: 'RAIN', resource: 'WI_RAIN', nightResource: 'WI_NIGHT_RAIN', labelShort: 'RAIN', labelLong: 'Rain' }],
    });

    expect(source).toContain('!strcmp(condition + len - 6, "_NIGHT")'); // strips the suffix
    expect(source).not.toContain('"RAIN_NIGHT"');                        // no separate night branch
    expect(source.match(/return "Rain";/g)).toHaveLength(1);             // day branch only
  });

  /** Both lookup functions must fall back to the configured labels for an unknown/null token. */
  test('ends each function with the configured fallback label', () => {
    const source = buildLabelsTable({
      fallback: FALLBACK,
      conditions: [{ token: 'RAIN', resource: 'WI_RAIN', labelShort: 'RAIN', labelLong: 'Rain' }],
    });

    expect(source).toContain('const char *wx_label_short_for_table');
    expect(source).toContain('const char *wx_label_long_for_table');
    expect(source).toContain('return "UNKNOWN";');
    expect(source).toContain('return "Unknown";');
  });

  /** Every shipped condition must reach both label tables - a dropped one renders the fallback. */
  test('covers every condition in the real vocabulary', () => {
    const source = buildLabelsTable(vocabulary);

    for (const { token, labelShort, labelLong } of vocabulary.conditions) {
      expect(source).toContain(`!strcmp(base, "${token}")`);
      expect(source).toContain(`return "${labelShort}";`);
      expect(source).toContain(`return "${labelLong}";`);
    }
  });
});
