#!/usr/bin/env node
/**
 * Generates the C weather-condition lookups from the shared vocabulary.
 *
 * Reads lib/ts/weather/conditions.ts (the single source of truth) and writes
 *   lib/c/pebble/ui/weather/icons_table.g.h          (token  -> icon resource)
 *   lib/c/pebble/ui/weather/icon_codes_table.g.h     (wire code -> icon resource)
 *   lib/c/pebble/ui/weather/labels_table.g.h         (token  -> short/long display label)
 *
 * Pure fs - no npm deps - so each face's wscript can run it under the SDK's node
 * with no node_modules install.
 *
 * Run via `npm run build:conditions`, or automatically by each face's build.
 */
import fs from 'node:fs';
import path from 'node:path';
import conditionVocabulary from '../ts/weather/conditions.ts';
import type { ConditionVocabulary } from '../ts/weather/conditions.ts';

const WEATHER_DIR = path.resolve(import.meta.dirname, '..', 'c', 'pebble', 'ui', 'weather');
const ICONS_OUT = path.join(WEATHER_DIR, 'icons_table.g.h');
const ICON_CODES_OUT = path.join(WEATHER_DIR, 'icon_codes_table.g.h');
const LABELS_OUT = path.join(WEATHER_DIR, 'labels_table.g.h');

function bannerLines() {
  return [
    '//------------------------------------------------------------------------------',
    '// <auto-generated>',
    '//     This code was generated by lib/tools/build-conditions.ts.',
    '//     Source: lib/ts/weather/conditions.ts',
    '//',
    '//     Changes to this file may be lost if the code is regenerated.',
    '//     Edit the source vocabulary and run `npm run build:conditions` instead.',
    '// </auto-generated>',
    '//------------------------------------------------------------------------------',
    '#pragma once',
    '',
  ];
}

/**
 * Builds the C icon-lookup source from a condition vocabulary.
 *
 * Pure string transform so it can be tested without touching the filesystem.
 * For each condition emits a token -> resource branch, and when the row has a
 * nightResource also emits a "<token>_NIGHT" -> nightResource branch (the wire
 * carries the _NIGHT token after dark).
 */
export function buildIconsTable({ fallback, conditions }: ConditionVocabulary) {
  const fallbackResource = `RESOURCE_ID_ICON_${fallback.resource}`;

  const lines = bannerLines();
  lines.push(
    `// resolves a condition token to its icon resource, falling back to ${fallback.resource}`,
    'static uint32_t wx_resource_for_table(const char *condition)',
    '{',
    '    if (!condition)',
    '    {',
    `        return ${fallbackResource};`,
    '    }',
    ''
  );

  for (const { token, resource, nightResource } of conditions) {
    lines.push(`    if (!strcmp(condition, "${token}"))`);
    lines.push('    {');
    lines.push(`        return RESOURCE_ID_ICON_${resource};`);
    lines.push('    }');
    lines.push('');

    if (nightResource) {
      lines.push(`    if (!strcmp(condition, "${token}_NIGHT"))`);
      lines.push('    {');
      lines.push(`        return RESOURCE_ID_ICON_${nightResource};`);
      lines.push('    }');
      lines.push('');
    }
  }

  lines.push(`    return ${fallbackResource};`);
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Builds the C code-lookup source from a condition vocabulary.
 *
 * The forecast row ships each condition as a single byte (its index in the
 * conditions array), optionally OR-ed with WX_FORECAST_NIGHT_BIT for an hour
 * after dark. This emits a switch on the base index that returns the night icon
 * when the bit is set (and the row has one) or the day icon otherwise. An index
 * that doesn't match a row falls back to the fallback glyph, which also covers
 * the UNKNOWN_CODE (255) the JS side sends for a mystery condition. Pure string
 * transform so it can be tested without the filesystem.
 */
export function buildIconCodesTable({ fallback, conditions }: ConditionVocabulary) {
  const fallbackResource = `RESOURCE_ID_ICON_${fallback.resource}`;

  const lines = bannerLines();
  lines.push(
    `// resolves a forecast condition code (index into the vocabulary) to its icon, picking the`,
    `// night glyph when WX_FORECAST_NIGHT_BIT is set and falling back to ${fallback.resource} for`,
    `// an unknown code`,
    '#include "ui/weather/icons.h"',
    '',
    'static uint32_t wx_resource_for_code(uint8_t code)',
    '{',
    '    bool night = (code & WX_FORECAST_NIGHT_BIT) != 0;',
    '    switch (code & ~WX_FORECAST_NIGHT_BIT)',
    '    {'
  );

  conditions.forEach(({ resource, nightResource }, index) => {
    const day = `RESOURCE_ID_ICON_${resource}`;
    const value = nightResource
      ? `night ? RESOURCE_ID_ICON_${nightResource} : ${day}`
      : day;
    lines.push(`    case ${index}: return ${value};`);
  });

  lines.push(
    `    default: return ${fallbackResource};`,
    '    }',
    '}',
    ''
  );

  return lines.join('\n');
}

/**
 * Builds one C label-lookup function (short or long) from the vocabulary.
 *
 * A night token reuses its day label, so the emitted function strips a trailing
 * "_NIGHT" from the input, then does one token -> label branch per condition
 * (half the branches of a day+night table). The suffix strip is a manual tail
 * compare (no strstr, which would pull in a big libc routine). Pure string transform.
 *
 * fnName is the C function name to emit, field is 'labelShort' or 'labelLong',
 * and fallbackText is the label returned for an unrecognized or null token.
 */
function buildLabelFn({ conditions }: ConditionVocabulary, fnName: string, field: 'labelShort' | 'labelLong', fallbackText: string) {
  const lines = [
    `static const char *${fnName}(const char *condition)`,
    '{',
    '    if (!condition)',
    '    {',
    `        return "${fallbackText}";`,
    '    }',
    '',
    '    // a night token reuses its day label, so drop a trailing "_NIGHT" before the lookup',
    '    char base[24];',
    '    size_t len = strlen(condition);',
    '    if (len > 6 && !strcmp(condition + len - 6, "_NIGHT"))',
    '    {',
    '        len -= 6;',
    '    }',
    '    if (len >= sizeof(base))',
    '    {',
    '        len = sizeof(base) - 1;',
    '    }',
    '    memcpy(base, condition, len);',
    "    base[len] = '\\0';",
    '',
  ];

  for (const condition of conditions) {
    const label = condition[field];
    lines.push(`    if (!strcmp(base, "${condition.token}"))`);
    lines.push('    {');
    lines.push(`        return "${label}";`);
    lines.push('    }');
    lines.push('');
  }

  lines.push(`    return "${fallbackText}";`);
  lines.push('}');
  lines.push('');

  return lines;
}

/** Builds the C label-lookup source (both short and long functions). */
export function buildLabelsTable(vocabulary: ConditionVocabulary) {
  const { fallback } = vocabulary;

  const lines = bannerLines();
  lines.push('#include <string.h>', '');
  lines.push(...buildLabelFn(vocabulary, 'wx_label_short_for_table', 'labelShort', fallback.labelShort));
  lines.push(...buildLabelFn(vocabulary, 'wx_label_long_for_table', 'labelLong', fallback.labelLong));

  return lines.join('\n');
}

function main() {
  const root = path.resolve(import.meta.dirname, '..', '..');

  fs.writeFileSync(ICONS_OUT, buildIconsTable(conditionVocabulary));
  fs.writeFileSync(ICON_CODES_OUT, buildIconCodesTable(conditionVocabulary));
  fs.writeFileSync(LABELS_OUT, buildLabelsTable(conditionVocabulary));

  console.log(`generated ${path.relative(root, ICONS_OUT)}, ${path.relative(root, ICON_CODES_OUT)} and ${path.relative(root, LABELS_OUT)} (${conditionVocabulary.conditions.length} conditions)`);
}

if (import.meta.main) {
  main();
}
