// GENERATED by tools/fonts/generate-bearing.py from resources/fonts/Teko-SemiBold.ttf
// Do not edit by hand. Rerun the generator after changing the value font.
//
// Per-glyph left ink offset (px) for the left-aligned Teko value fonts, so the draw
// code can shift a value to land its first glyph's ink at the same inset no matter
// which character leads. = round(lsb * size / unitsPerEm), verified against the
// emulator. Indexed by (char - 32) over printable ASCII. See gh_value_left.
#pragma once
#include "draw/fonts.h"

// FONT_TEKO_26 (26px)
static const int8_t s_ink_off_26[95] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 3, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2 };

// FONT_TEKO_24 (24px)
static const int8_t s_ink_off_24[95] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2 };

// FONT_TEKO_22 (22px)
static const int8_t s_ink_off_22[95] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2 };

// px to add to a value's left pad so its first glyph's ink sits at the target inset,
// which is 1px in to clear the border (matching EDGE_PAD, border-independent so the
// value does not shift when the border is toggled). Returns 0 for fonts this table
// does not cover (leaves them untouched).
static inline int value_bearing_fix(char first, FontId font)
{
    const int8_t *table;
    switch (font)
    {
        case FONT_TEKO_26: table = s_ink_off_26; break;
        case FONT_TEKO_24: table = s_ink_off_24; break;
        case FONT_TEKO_22: table = s_ink_off_22; break;
        default: return 0;
    }
    unsigned index = (unsigned char)first - 32u;
    if (index >= 95u) { return 0; }
    return 1 - table[index];
}
